
	<!-- Start Add Social Bookmark Buttons - small buttons - blogknowhow.blogspot.com -->
<a style="text-decoration:none;" href="http://digg.com/" rel="nofollow" onclick="window.open('http://digg.com/submit?phase=2&amp;url='+encodeURIComponent(<?php echo "'$href'"; ?>)+'&amp;bodytext=&amp;tags=&amp;title='+encodeURIComponent(<?php echo "'$title'"; ?>));return false;" title="Bookmark to: Digg"> <img width="24" height="24" border="0" id="Digg" style="padding-bottom:1px;" alt="Bookmark Digg" src="http://4.bp.blogspot.com/_vLeiVavkV_M/Sn0FwVnXcQI/AAAAAAAABf8/8t8jUbCOQN0/s200/digg.png" name="Digg"/> </a>
  <a style="text-decoration:none;" href="http://del.icio.us/" rel="nofollow" onclick="window.open('http://del.icio.us/post?v=2&amp;url='+encodeURIComponent(<?php echo "'$href'"; ?>)+'&amp;notes=&amp;tags=&amp;title='+encodeURIComponent(<?php echo "'$title'"; ?>));return false;" title="Bookmark to: Del.icio.us"> <img width="24" height="24" border="0" id="Delicious" style="padding-bottom:1px;" alt="Bookmark Del.icio.us" src="http://4.bp.blogspot.com/_vLeiVavkV_M/Sn0FmrXO-vI/AAAAAAAABf0/gK0oKdOJzMM/s200/delicious.png" name="Delicious"/> </a>
  <a style="text-decoration:none;" href="http://www.facebook.com/" rel="nofollow" onclick="window.open('http://www.facebook.com/sharer.php?u='+encodeURIComponent(<?php echo "'$href'"; ?>)+'&amp;t='+encodeURIComponent(<?php echo "'$title'"; ?>));return false;" title="Bookmark to: Facebook"> <img width="24" height="24" border="0" id="Facebook" style="padding-bottom:1px;" alt="Bookmark Facebook" src="http://1.bp.blogspot.com/_vLeiVavkV_M/Sn0F1uQ7P_I/AAAAAAAABgE/zESf9tLZOtw/s200/facebook.png" name="Facebook"/> </a>
  <a style="text-decoration:none;" href="http://reddit.com/" rel="nofollow" onclick="window.open('http://reddit.com/submit?url='+encodeURIComponent(<?php echo "'$href'"; ?>)+'&amp;title='+encodeURIComponent(<?php echo "'$title'"; ?>));return false;" title="Bookmark to: Reddit"> <img width="24" height="24" border="0" id="Reddit" style="padding-bottom:1px;" alt="Bookmark Reddit" src="http://3.bp.blogspot.com/_vLeiVavkV_M/Sn0GDJUzotI/AAAAAAAABgU/qAA0KjdLgF8/s200/reddit.png" name="Reddit"/> </a>
  <a style="text-decoration:none;" href="http://www.stumbleupon.com/" rel="nofollow" onclick="window.open('http://www.stumbleupon.com/submit?url='+encodeURIComponent(<?php echo "'$href'"; ?>)+'&amp;title='+encodeURIComponent(<?php echo "'$title'"; ?>));return false;" title="Bookmark to: StumbleUpon"> <img width="24" height="24" border="0" id="StumbleUpon" style="padding-bottom:1px;" alt="Bookmark StumbleUpon" src="http://4.bp.blogspot.com/_vLeiVavkV_M/Sn0GJ5NxMRI/AAAAAAAABgc/zaraJzCuyXI/s200/stumbleupon.png" name="StumbleUpon"/> </a>
  <a style="text-decoration:none;" href="http://www.yahoo.com/" rel="nofollow" onclick="window.open('http://myweb2.search.yahoo.com/myresults/bookmarklet?t='+encodeURIComponent(<?php echo "'$title'"; ?>)+'&amp;d=&amp;tag=&amp;u='+encodeURIComponent(<?php echo "'$href'"; ?>));return false;" title="Bookmark to: Yahoo"> <img width="24" height="24" border="0" id="Yahoo" style="padding-bottom:1px;" alt="Bookmark Yahoo" src="http://2.bp.blogspot.com/_vLeiVavkV_M/Sn0GdCPWuUI/AAAAAAAABg0/-tjcrdMnRkA/s200/yahoo.png" name="Yahoo"/> </a>
  <a style="text-decoration:none;" href="http://www.google.com/" rel="nofollow" onclick="window.open('http://www.google.com/bookmarks/mark?op=add&amp;bkmk='+encodeURIComponent(<?php echo "'$href'"; ?>)+'&amp;annotation=&amp;labels=&amp;title='+encodeURIComponent(<?php echo "'$title'"; ?>));return false;" title="Bookmark to: Google"> <img width="24" height="24" border="0" id="Google" style="padding-bottom:1px;" alt="Bookmark Google" src="http://3.bp.blogspot.com/_vLeiVavkV_M/Sn0F7200sZI/AAAAAAAABgM/ivmXOn18EZA/s200/google.png" name="Google"/> </a>
  <a style="text-decoration:none;" href="http://www.technorati.com/" rel="nofollow" onclick="window.open('http://technorati.com/faves?add='+encodeURIComponent(<?php echo "'$href'"; ?>)+'&amp;tag=');return false;" title="Bookmark to: Technorati"> <img width="24" height="24" border="0" id="Technorati" style="padding-bottom:1px;" alt="Bookmark Technorati" src="http://4.bp.blogspot.com/_vLeiVavkV_M/Sn0GRQk71JI/AAAAAAAABgk/AT5wC4ZYB8g/s200/technorati.png" name="Technorati"/> </a>
  <a style="text-decoration:none;" href="http://twitter.com/" target="_Blank" rel="nofollow" onclick=" window.open('http://twitter.com/home?status='+encodeURIComponent(<?php echo "'$title'"; ?>)+'%20'+encodeURIComponent(<?php echo "'$href'"; ?>)); return false;" title="Twitter"> <img width="24" height="24" border="0" id="Twitter" style="padding-bottom:1px;" alt="Bookmark Twitter" src="http://2.bp.blogspot.com/_vLeiVavkV_M/Sn0GYqWEWAI/AAAAAAAABgs/8715Vd67VtA/s200/twitter.png" name="Twitter"/> </a>
<!-- End Add Social Bookmark Buttons - small buttons - blogknowhow.blogspot.com -->